### PR TITLE
Carve strikes again

### PR DESCRIPTION
**Pull request by xrl**
Here's a stab at making `MmapView` meet my needs. Consume a `MmapView` in to many `MmapView`, but more than `split_at`.

### CODE REVIEW

**Comment by xrl** [comment]
@danburkert heres an example using some of your feedback from my other PR. Could this become suitable for merging in? The big thing remaining is to check that subviews don't overlap.

**Comment by danburkert** [comment]
@xrl I'm a bit torn on this.  I can see a lot of variants on this theme, and I'm not keen on supplying them all in the crate.  There are a few issues with the API: are the offsets and lengths specified relative to the start of the `mmap` (this is what is implemented), or relative to the previous subview (also a valid interpretation), should we supply both?  What if the subviews are overlapping (this would be totally unsafe, and should be checked for).  What about a variant that assumes no space between subviews, and just takes a slice of offsets (and what happens if these are specified in non-sort order)?  Also, we would need corresponding variants for `MmapViewSync`.

At this point I don't want to go down the road of adding all of these to that API, but I'm willing to reconsider if it becomes a common operation when using the library.  I *do* want to make it easy to implement these things yourself, though.  So if you find any more primitive operations on `Mmap` or views that would make it easy to implement higher-level methods like carve, definitely let me know.

**Comment by xrl** [comment]
@danburkert cool, I get that this is more a "useful mmap pattern" and less a "stuff you absolutely need to be a mmap implementation".

But this implementation is centered on offset/len relative to the view -- this is a recursive/relative pattern. I have no need for the other patterns but I see what you're saying. The current code is incorrect to have offset/len of subviews relative to root `Mmap` (whoops).

What's a good API to facilitate consuming a `MmapView` in to many non-overlapping `MmapView`s? Perhaps a method in the spirit of `from_raw_parts`?

**Comment by xrl** [comment]
To be clear, the proposed `subview` method from #11 would only allow further limiting a view to a more restrictive view, not multiple more restrictive views.

**Comment by danburkert** [comment]
@xrl: right, but it should be straightforward to carve up the views however you see fit using either `split_at`, or `restrict` (renamed from `subview`).  What I'm concerned about is that everyone is going to want to carve up the mmap differently, so adding usecase specific carving functions will quickly get out of hand.

**Comment by xrl** [comment]
What about providing a constructor for `MmapView`? Then my application code could implement the `carve` behavior and handle the single consumption, multiple views issue?

**Comment by danburkert** [comment]
@xrl are you attempting to have multiple `MmapView`s reference the same piece of the mmap?  That is possible with the implementation in this PR, but it's not safe.  `MmapView`s should not reference the same piece of the mmap at any time, by making the constructor private and not providing a `clone` impl this invariant is enforced.

**Comment by xrl** [comment]
@danburkert exactly, I need to have multiple views of the same `Mmap`. I understand that this is unsafe. It could be this only works with the `Rc` implementation.

**Comment by xrl** [comment]
Also, to be clear: splitting a `MmapView` in to many `MmapView`s could be unsafe if invariants are not checked, but a single-threaded Rc implementation would be safe. `carve` would scope the mmap to multiple smaller sections of memory, and by consuming the intermediate containers you are safe.

**Comment by danburkert** [comment]
Oh sorry I missed your message above that said specifically non-overlapping views.  So if you are specifying your offsets relative to the previous view, it could looks something like this (untested):

```rust
pub fn carve(mut view: MmapView, ranges: &[(usize, usize)]) -> Result<Vec<MmapView>> {
    let mut views = Vec::with_capacity(ranges.len());
    for &(offset, len) in ranges {
        let total_len = view.len();
        try!(view.restrict(offset, total_len));
        let (v, remaining) = try!(view.split_at(len));
        views.push(v);
        view = remaining;
    };
    Ok(views)
}
```

**Comment by xrl** [comment]
Oh, good idea. Let me see how this goes.

**Comment by xrl** [comment]
This has been working just dandy.

**Pull request closed without merging**
