### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by dekellum**
I've had my share of doubts on correct usage of _memmap-rs_, many of which I was eventually able to clear up by searching the github issues and PR's merged or closed.   In this PR I attempt to document some basics that I hope are non-controversial and specific to the rust wrapping.  Some of the changes are just rustdoc niceties like links.

This [comment](https://github.com/danburkert/memmap-rs/issues/49#issuecomment-319233236) in #49 was super helpful to me, and I've tried to restate it here in terms of relative lifetimes. 

The unmerged `try_clone` part of #61 prompted me to try using `Arc<Mmap>`, and I've mentioned that usage in the doc, as I think it can add clarity around possible threaded access and lifetime. 

This likely only addresses a small fraction of what was requested in #47, but is it not a worthy improvement?

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @dekellum! This looks like a nice improvement to me. What do you think @danburkert?

**Comment by danburkert** [comment]
Thanks!  I squashed this and merged it directly to master along with a few tweaks (I didn't have permission to push to your branch, so couldn't do it through the PR interface).

**Comment by dekellum** [comment]
Oh OK, thanks for the effective merge-squash, with your edits, in 3b047cc.  I wasn't aware of RFC 1946 style linking, as per part of your edits. Do you expect that this will work properly on docs.rs upon the next release?

**Comment by jonhoo** [comment]
@danburkert any chance you could cut a new release so that these documentation improvements make it to docs.rs?

**Pull request closed without merging**
